### ISSUE TITLE
Consent failure

### ISSUE THREAD

**Issue by TheFrozenFire** [tpopela/fedora-user-agent-chrome#1]
I didn't consent to having this extension installed in my browser. Why did this get surreptitiously installed?

**Comment by tpopela** [comment]
The automatic installation of this extension is triggered by fedora-user-agent-chrome package[0] that is part of Fedora Workstation product.

[0] - https://admin.fedoraproject.org/pkgdb/package/fedora-user-agent-chrome/

**Comment by sgnl05** [comment]
This package should be an optional install in Fedora. Forcing third party extensions on peoples computer is a bad idea!

**Comment by c0b** [comment]
:+1: see #2 

> install without consent is very bad!!!
