### ISSUE TITLE
Can't get to Gitlab's Sign In page

### ISSUE THREAD

**Issue by pdrylo** [tpopela/fedora-user-agent-chrome#11]
When going to https://gitlab.com/users/sign_in with extension enabled I'm stuck on 
![image](https://user-images.githubusercontent.com/3886451/163167542-16e15c72-fffa-483f-9dd2-c0e79aff48da.png)
screen with 503 error returned from Gitlab saying Javascript has to be enabled. As soon as the extension gets disabled proper Sign in form is presented.

Additional information: This extension stopped working after upgrading to Chrome 100.

**Comment by tpopela** [comment]
The extension works as expected even with Chrome 100 - see `Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36`. From my point of view GitLab isn't handling the "Chrome 100" situation well (if it broke after the 99 -> 100 update and honestly we're not touching that part of the UA at all) - have you tried to open a support issue with them?

**Comment by tpopela** [comment]
This has been reported as https://gitlab.com/gitlab-org/gitlab/-/issues/358802

**Comment by pdrylo** [comment]
Thanks for that gitlab issue reference @tpopela

**Comment by tpopela** [comment]
If anyone who comes here have a GitLab account, then please "thumbs-up" the issue in GitLab.

**Comment by sgallagher** [comment]
Hmm, it appears this is also an issue on any site that uses CloudFlare's DDoS protection. Looking at the JS source for Gitlab, it's using CloudFlare as well (just rebranded). So I think this is a bigger issue than we thought (but also still fixable in just one place).
