### ISSUE TITLE
Publish privacy practices on Chrome Web Store

### ISSUE THREAD

**Issue by pgn674** [tpopela/fedora-user-agent-chrome#14]
When I have this extension installed, Google Chrome's [extensions management page](chrome://extensions/) shows "This extension hasn't published privacy practices, such as how it collects and uses data". The extension's page on the [Chrome Web Store](https://chromewebstore.google.com/detail/Fedora%20User%20Agent/hojggiaghnldpcknpbciehjcaoafceil) shows "This extension may soon no longer be supported because it doesn't follow best practices for Chrome extensions" and "The developer has not provided any information about the collection or usage of your data."

**Comment by tpopela** [comment]
Thank you for your report. It actually reminded me that I promised to unpublish the extension in https://discussion.fedoraproject.org/t/announcement-removal-of-fedora-from-browsers-user-agent-string/38835 so I've finally done it.
