### ISSUE TITLE
`install without consent is very bad!!!`

### ISSUE THREAD

**Issue by c0b** [tpopela/fedora-user-agent-chrome#2]
I have given 1 star review that's very bad; this plugin is doing advertising only without anything else

> install without consent is very bad!!!

I have reported abuse and call for more can report there

https://chrome.google.com/webstore/report/hojggiaghnldpcknpbciehjcaoafceil?hl=en-US&gl=US

**Comment by tpopela** [comment]
Please see https://bugzilla.redhat.com/show_bug.cgi?id=1266569
