### ISSUE TITLE
Support for Chromium

### ISSUE THREAD

**Issue by mkrawiec** [tpopela/fedora-user-agent-chrome#4]
Now that we have official chromium packages in Fedora repos, it would be nice if this package supported it.

**Comment by tpopela** [comment]
This package supports it, but the file that's doing the auto-install needs to be installed under /usr/share/chromium/extensions as well. You can test the updated Fedora packages here:

f23 - https://bodhi.fedoraproject.org/updates/FEDORA-2016-507a178f1f
f24 - https://bodhi.fedoraproject.org/updates/FEDORA-2016-d794baffa1
f25 - https://bodhi.fedoraproject.org/updates/FEDORA-2016-94f8be40ff
