### ISSUE TITLE
WebSocket headers not modified

### ISSUE THREAD

**Issue by adamrmartinson** [tpopela/fedora-user-agent-chrome#8]
When opening a WebSocket connection, the original User-Agent header is sent (matches navigator.userAgent, doesn't include "Fedora").  The same might apply to EventSource connections.

Many sites (including ours) use the User-Agent for PHP session security; if it doesn't match, the session is invalidated.

**Comment by tpopela** [comment]
Thank you for the bug report! It will be fixed in 0.0.0.6 release that will roll soon.
