### ISSUE TITLE
Agent changed to often

### ISSUE THREAD

**Issue by badcel** [tpopela/fedora-user-agent-chrome#9]
It looks like the agent is changed, even if the agent has already been updated:

User-Agent: Mozilla/5.0 (X11; **Fedora; Fedora;** Linux x86_64) AppleWebKit/...

compare to another call:

User-Agent: Mozilla/5.0 (X11; **Fedora**; Linux x86_64) AppleWebKit/...

This is probably related with a http redirect.

**Comment by tpopela** [comment]
Thank you for the bug report! It will be fixed in 0.0.0.6 release that will roll soon.
